// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: proto/demoroo_api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BranchSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchText string `protobuf:"bytes,1,opt,name=SearchText,proto3" json:"SearchText,omitempty"`
}

func (x *BranchSearchRequest) Reset() {
	*x = BranchSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demoroo_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchSearchRequest) ProtoMessage() {}

func (x *BranchSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demoroo_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchSearchRequest.ProtoReflect.Descriptor instead.
func (*BranchSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_demoroo_api_proto_rawDescGZIP(), []int{0}
}

func (x *BranchSearchRequest) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

type BranchSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results    []*BranchSearchResultItem `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	TotalCount int32                     `protobuf:"varint,2,opt,name=TotalCount,proto3" json:"TotalCount,omitempty"`
}

func (x *BranchSearchResponse) Reset() {
	*x = BranchSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demoroo_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchSearchResponse) ProtoMessage() {}

func (x *BranchSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demoroo_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchSearchResponse.ProtoReflect.Descriptor instead.
func (*BranchSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_demoroo_api_proto_rawDescGZIP(), []int{1}
}

func (x *BranchSearchResponse) GetResults() []*BranchSearchResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BranchSearchResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BranchSearchResultItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Alt  bool   `protobuf:"varint,3,opt,name=Alt,proto3" json:"Alt,omitempty"`
}

func (x *BranchSearchResultItem) Reset() {
	*x = BranchSearchResultItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_demoroo_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BranchSearchResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchSearchResultItem) ProtoMessage() {}

func (x *BranchSearchResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_demoroo_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchSearchResultItem.ProtoReflect.Descriptor instead.
func (*BranchSearchResultItem) Descriptor() ([]byte, []int) {
	return file_proto_demoroo_api_proto_rawDescGZIP(), []int{2}
}

func (x *BranchSearchResultItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BranchSearchResultItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BranchSearchResultItem) GetAlt() bool {
	if x != nil {
		return x.Alt
	}
	return false
}

var File_proto_demoroo_api_proto protoreflect.FileDescriptor

var file_proto_demoroo_api_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x65, 0x6d, 0x6f, 0x72, 0x6f, 0x6f, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x13, 0x42, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x69, 0x0a, 0x14, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x42, 0x72, 0x61, 0x6e,
	0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x54,
	0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4e, 0x0a, 0x16, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x41, 0x6c, 0x74, 0x32, 0x4c, 0x0a, 0x13, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x14, 0x2e, 0x42,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x42, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_demoroo_api_proto_rawDescOnce sync.Once
	file_proto_demoroo_api_proto_rawDescData = file_proto_demoroo_api_proto_rawDesc
)

func file_proto_demoroo_api_proto_rawDescGZIP() []byte {
	file_proto_demoroo_api_proto_rawDescOnce.Do(func() {
		file_proto_demoroo_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_demoroo_api_proto_rawDescData)
	})
	return file_proto_demoroo_api_proto_rawDescData
}

var file_proto_demoroo_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_demoroo_api_proto_goTypes = []interface{}{
	(*BranchSearchRequest)(nil),    // 0: BranchSearchRequest
	(*BranchSearchResponse)(nil),   // 1: BranchSearchResponse
	(*BranchSearchResultItem)(nil), // 2: BranchSearchResultItem
}
var file_proto_demoroo_api_proto_depIdxs = []int32{
	2, // 0: BranchSearchResponse.Results:type_name -> BranchSearchResultItem
	0, // 1: BranchSearchService.Search:input_type -> BranchSearchRequest
	1, // 2: BranchSearchService.Search:output_type -> BranchSearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_demoroo_api_proto_init() }
func file_proto_demoroo_api_proto_init() {
	if File_proto_demoroo_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_demoroo_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_demoroo_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_demoroo_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BranchSearchResultItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_demoroo_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_demoroo_api_proto_goTypes,
		DependencyIndexes: file_proto_demoroo_api_proto_depIdxs,
		MessageInfos:      file_proto_demoroo_api_proto_msgTypes,
	}.Build()
	File_proto_demoroo_api_proto = out.File
	file_proto_demoroo_api_proto_rawDesc = nil
	file_proto_demoroo_api_proto_goTypes = nil
	file_proto_demoroo_api_proto_depIdxs = nil
}
